### ISSUE TITLE
Write README

### ISSUE THREAD

**Issue by tigerANrex** [tigerANrex/Automatic_Survey_Scraper#6]
* Type a description of what this tool does.
* Create a list of tools we used
* List of prerequisite tools needed before this can work

**Comment by tigerANrex** [comment]
Can one of you or both type this out, and I can do all the formatting later.

**Comment by jasih** [comment]
[readmedraft.txt](https://github.com/tigerANrex/Automatic_Survey_Scraper/files/3805160/readmedraft.txt)
dunno if I did it right but here you go

**Comment by tigerANrex** [comment]
Good enough for me. @betacone if you wanna add something to it you can.
